// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merkledag.proto

package merkledag.pb;

public final class Merkledag {
  private Merkledag() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PBLinkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:merkledag.pb.PBLink)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * multihash of the target object
     * </pre>
     *
     * <code>optional bytes Hash = 1;</code>
     * @return Whether the hash field is set.
     */
    boolean hasHash();
    /**
     * <pre>
     * multihash of the target object
     * </pre>
     *
     * <code>optional bytes Hash = 1;</code>
     * @return The hash.
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <pre>
     * utf string name. should be unique per object
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <pre>
     * utf string name. should be unique per object
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <pre>
     * utf string name. should be unique per object
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * cumulative size of target object
     * </pre>
     *
     * <code>optional uint64 Tsize = 3;</code>
     * @return Whether the tsize field is set.
     */
    boolean hasTsize();
    /**
     * <pre>
     * cumulative size of target object
     * </pre>
     *
     * <code>optional uint64 Tsize = 3;</code>
     * @return The tsize.
     */
    long getTsize();
  }
  /**
   * <pre>
   * An IPFS MerkleDAG Link
   * </pre>
   *
   * Protobuf type {@code merkledag.pb.PBLink}
   */
  public static final class PBLink extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:merkledag.pb.PBLink)
      PBLinkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PBLink.newBuilder() to construct.
    private PBLink(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBLink() {
      hash_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PBLink();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBLink(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              hash_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              tsize_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Merkledag.internal_static_merkledag_pb_PBLink_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Merkledag.internal_static_merkledag_pb_PBLink_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBLink.class, Builder.class);
    }

    private int bitField0_;
    public static final int HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString hash_;
    /**
     * <pre>
     * multihash of the target object
     * </pre>
     *
     * <code>optional bytes Hash = 1;</code>
     * @return Whether the hash field is set.
     */
    @Override
    public boolean hasHash() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * multihash of the target object
     * </pre>
     *
     * <code>optional bytes Hash = 1;</code>
     * @return The hash.
     */
    @Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <pre>
     * utf string name. should be unique per object
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     * @return Whether the name field is set.
     */
    @Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * utf string name. should be unique per object
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * utf string name. should be unique per object
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TSIZE_FIELD_NUMBER = 3;
    private long tsize_;
    /**
     * <pre>
     * cumulative size of target object
     * </pre>
     *
     * <code>optional uint64 Tsize = 3;</code>
     * @return Whether the tsize field is set.
     */
    @Override
    public boolean hasTsize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * cumulative size of target object
     * </pre>
     *
     * <code>optional uint64 Tsize = 3;</code>
     * @return The tsize.
     */
    @Override
    public long getTsize() {
      return tsize_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, hash_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, tsize_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, hash_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, tsize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBLink)) {
        return super.equals(obj);
      }
      PBLink other = (PBLink) obj;

      if (hasHash() != other.hasHash()) return false;
      if (hasHash()) {
        if (!getHash()
            .equals(other.getHash())) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasTsize() != other.hasTsize()) return false;
      if (hasTsize()) {
        if (getTsize()
            != other.getTsize()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHash()) {
        hash = (37 * hash) + HASH_FIELD_NUMBER;
        hash = (53 * hash) + getHash().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasTsize()) {
        hash = (37 * hash) + TSIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTsize());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBLink parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLink parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLink parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLink parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLink parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLink parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLink parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLink parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLink parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBLink parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLink parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLink parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBLink prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An IPFS MerkleDAG Link
     * </pre>
     *
     * Protobuf type {@code merkledag.pb.PBLink}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:merkledag.pb.PBLink)
        PBLinkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Merkledag.internal_static_merkledag_pb_PBLink_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Merkledag.internal_static_merkledag_pb_PBLink_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBLink.class, Builder.class);
      }

      // Construct using merkledag.pb.Merkledag.PBLink.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        hash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tsize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Merkledag.internal_static_merkledag_pb_PBLink_descriptor;
      }

      @Override
      public PBLink getDefaultInstanceForType() {
        return PBLink.getDefaultInstance();
      }

      @Override
      public PBLink build() {
        PBLink result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PBLink buildPartial() {
        PBLink result = new PBLink(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.tsize_ = tsize_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBLink) {
          return mergeFrom((PBLink)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBLink other) {
        if (other == PBLink.getDefaultInstance()) return this;
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasTsize()) {
          setTsize(other.getTsize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBLink parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBLink) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * multihash of the target object
       * </pre>
       *
       * <code>optional bytes Hash = 1;</code>
       * @return Whether the hash field is set.
       */
      @Override
      public boolean hasHash() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * multihash of the target object
       * </pre>
       *
       * <code>optional bytes Hash = 1;</code>
       * @return The hash.
       */
      @Override
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <pre>
       * multihash of the target object
       * </pre>
       *
       * <code>optional bytes Hash = 1;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * multihash of the target object
       * </pre>
       *
       * <code>optional bytes Hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       * utf string name. should be unique per object
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * utf string name. should be unique per object
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * utf string name. should be unique per object
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * utf string name. should be unique per object
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * utf string name. should be unique per object
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * utf string name. should be unique per object
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private long tsize_ ;
      /**
       * <pre>
       * cumulative size of target object
       * </pre>
       *
       * <code>optional uint64 Tsize = 3;</code>
       * @return Whether the tsize field is set.
       */
      @Override
      public boolean hasTsize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * cumulative size of target object
       * </pre>
       *
       * <code>optional uint64 Tsize = 3;</code>
       * @return The tsize.
       */
      @Override
      public long getTsize() {
        return tsize_;
      }
      /**
       * <pre>
       * cumulative size of target object
       * </pre>
       *
       * <code>optional uint64 Tsize = 3;</code>
       * @param value The tsize to set.
       * @return This builder for chaining.
       */
      public Builder setTsize(long value) {
        bitField0_ |= 0x00000004;
        tsize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * cumulative size of target object
       * </pre>
       *
       * <code>optional uint64 Tsize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTsize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tsize_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:merkledag.pb.PBLink)
    }

    // @@protoc_insertion_point(class_scope:merkledag.pb.PBLink)
    private static final PBLink DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBLink();
    }

    public static PBLink getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<PBLink>
        PARSER = new com.google.protobuf.AbstractParser<PBLink>() {
      @Override
      public PBLink parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBLink(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBLink> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PBLink> getParserForType() {
      return PARSER;
    }

    @Override
    public PBLink getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:merkledag.pb.PBNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    java.util.List<PBLink>
        getLinksList();
    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    PBLink getLinks(int index);
    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    int getLinksCount();
    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    java.util.List<? extends PBLinkOrBuilder>
        getLinksOrBuilderList();
    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    PBLinkOrBuilder getLinksOrBuilder(
        int index);

    /**
     * <pre>
     * opaque user data
     * </pre>
     *
     * <code>optional bytes Data = 1;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <pre>
     * opaque user data
     * </pre>
     *
     * <code>optional bytes Data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * An IPFS MerkleDAG Node
   * </pre>
   *
   * Protobuf type {@code merkledag.pb.PBNode}
   */
  public static final class PBNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:merkledag.pb.PBNode)
      PBNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PBNode.newBuilder() to construct.
    private PBNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBNode() {
      links_ = java.util.Collections.emptyList();
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PBNode();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                links_ = new java.util.ArrayList<PBLink>();
                mutable_bitField0_ |= 0x00000001;
              }
              links_.add(
                  input.readMessage(PBLink.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          links_ = java.util.Collections.unmodifiableList(links_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Merkledag.internal_static_merkledag_pb_PBNode_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Merkledag.internal_static_merkledag_pb_PBNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBNode.class, Builder.class);
    }

    private int bitField0_;
    public static final int LINKS_FIELD_NUMBER = 2;
    private java.util.List<PBLink> links_;
    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    @Override
    public java.util.List<PBLink> getLinksList() {
      return links_;
    }
    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    @Override
    public java.util.List<? extends PBLinkOrBuilder>
        getLinksOrBuilderList() {
      return links_;
    }
    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    @Override
    public int getLinksCount() {
      return links_.size();
    }
    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    @Override
    public PBLink getLinks(int index) {
      return links_.get(index);
    }
    /**
     * <pre>
     * refs to other objects
     * </pre>
     *
     * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
     */
    @Override
    public PBLinkOrBuilder getLinksOrBuilder(
        int index) {
      return links_.get(index);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * opaque user data
     * </pre>
     *
     * <code>optional bytes Data = 1;</code>
     * @return Whether the data field is set.
     */
    @Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * opaque user data
     * </pre>
     *
     * <code>optional bytes Data = 1;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, data_);
      }
      for (int i = 0; i < links_.size(); i++) {
        output.writeMessage(2, links_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      for (int i = 0; i < links_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, links_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBNode)) {
        return super.equals(obj);
      }
      PBNode other = (PBNode) obj;

      if (!getLinksList()
          .equals(other.getLinksList())) return false;
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLinksCount() > 0) {
        hash = (37 * hash) + LINKS_FIELD_NUMBER;
        hash = (53 * hash) + getLinksList().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An IPFS MerkleDAG Node
     * </pre>
     *
     * Protobuf type {@code merkledag.pb.PBNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:merkledag.pb.PBNode)
        PBNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Merkledag.internal_static_merkledag_pb_PBNode_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Merkledag.internal_static_merkledag_pb_PBNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBNode.class, Builder.class);
      }

      // Construct using merkledag.pb.Merkledag.PBNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLinksFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (linksBuilder_ == null) {
          links_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          linksBuilder_.clear();
        }
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Merkledag.internal_static_merkledag_pb_PBNode_descriptor;
      }

      @Override
      public PBNode getDefaultInstanceForType() {
        return PBNode.getDefaultInstance();
      }

      @Override
      public PBNode build() {
        PBNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PBNode buildPartial() {
        PBNode result = new PBNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (linksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            links_ = java.util.Collections.unmodifiableList(links_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.links_ = links_;
        } else {
          result.links_ = linksBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBNode) {
          return mergeFrom((PBNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBNode other) {
        if (other == PBNode.getDefaultInstance()) return this;
        if (linksBuilder_ == null) {
          if (!other.links_.isEmpty()) {
            if (links_.isEmpty()) {
              links_ = other.links_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLinksIsMutable();
              links_.addAll(other.links_);
            }
            onChanged();
          }
        } else {
          if (!other.links_.isEmpty()) {
            if (linksBuilder_.isEmpty()) {
              linksBuilder_.dispose();
              linksBuilder_ = null;
              links_ = other.links_;
              bitField0_ = (bitField0_ & ~0x00000001);
              linksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLinksFieldBuilder() : null;
            } else {
              linksBuilder_.addAllMessages(other.links_);
            }
          }
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PBLink> links_ =
        java.util.Collections.emptyList();
      private void ensureLinksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          links_ = new java.util.ArrayList<PBLink>(links_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PBLink, PBLink.Builder, PBLinkOrBuilder> linksBuilder_;

      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public java.util.List<PBLink> getLinksList() {
        if (linksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(links_);
        } else {
          return linksBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public int getLinksCount() {
        if (linksBuilder_ == null) {
          return links_.size();
        } else {
          return linksBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public PBLink getLinks(int index) {
        if (linksBuilder_ == null) {
          return links_.get(index);
        } else {
          return linksBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public Builder setLinks(
          int index, PBLink value) {
        if (linksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinksIsMutable();
          links_.set(index, value);
          onChanged();
        } else {
          linksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public Builder setLinks(
          int index, PBLink.Builder builderForValue) {
        if (linksBuilder_ == null) {
          ensureLinksIsMutable();
          links_.set(index, builderForValue.build());
          onChanged();
        } else {
          linksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public Builder addLinks(PBLink value) {
        if (linksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinksIsMutable();
          links_.add(value);
          onChanged();
        } else {
          linksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public Builder addLinks(
          int index, PBLink value) {
        if (linksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinksIsMutable();
          links_.add(index, value);
          onChanged();
        } else {
          linksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public Builder addLinks(
          PBLink.Builder builderForValue) {
        if (linksBuilder_ == null) {
          ensureLinksIsMutable();
          links_.add(builderForValue.build());
          onChanged();
        } else {
          linksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public Builder addLinks(
          int index, PBLink.Builder builderForValue) {
        if (linksBuilder_ == null) {
          ensureLinksIsMutable();
          links_.add(index, builderForValue.build());
          onChanged();
        } else {
          linksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public Builder addAllLinks(
          Iterable<? extends PBLink> values) {
        if (linksBuilder_ == null) {
          ensureLinksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, links_);
          onChanged();
        } else {
          linksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public Builder clearLinks() {
        if (linksBuilder_ == null) {
          links_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          linksBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public Builder removeLinks(int index) {
        if (linksBuilder_ == null) {
          ensureLinksIsMutable();
          links_.remove(index);
          onChanged();
        } else {
          linksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public PBLink.Builder getLinksBuilder(
          int index) {
        return getLinksFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public PBLinkOrBuilder getLinksOrBuilder(
          int index) {
        if (linksBuilder_ == null) {
          return links_.get(index);  } else {
          return linksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public java.util.List<? extends PBLinkOrBuilder>
           getLinksOrBuilderList() {
        if (linksBuilder_ != null) {
          return linksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(links_);
        }
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public PBLink.Builder addLinksBuilder() {
        return getLinksFieldBuilder().addBuilder(
            PBLink.getDefaultInstance());
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public PBLink.Builder addLinksBuilder(
          int index) {
        return getLinksFieldBuilder().addBuilder(
            index, PBLink.getDefaultInstance());
      }
      /**
       * <pre>
       * refs to other objects
       * </pre>
       *
       * <code>repeated .merkledag.pb.PBLink Links = 2;</code>
       */
      public java.util.List<PBLink.Builder>
           getLinksBuilderList() {
        return getLinksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PBLink, PBLink.Builder, PBLinkOrBuilder>
          getLinksFieldBuilder() {
        if (linksBuilder_ == null) {
          linksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PBLink, PBLink.Builder, PBLinkOrBuilder>(
                  links_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          links_ = null;
        }
        return linksBuilder_;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * opaque user data
       * </pre>
       *
       * <code>optional bytes Data = 1;</code>
       * @return Whether the data field is set.
       */
      @Override
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * opaque user data
       * </pre>
       *
       * <code>optional bytes Data = 1;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * opaque user data
       * </pre>
       *
       * <code>optional bytes Data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * opaque user data
       * </pre>
       *
       * <code>optional bytes Data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:merkledag.pb.PBNode)
    }

    // @@protoc_insertion_point(class_scope:merkledag.pb.PBNode)
    private static final PBNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBNode();
    }

    public static PBNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<PBNode>
        PARSER = new com.google.protobuf.AbstractParser<PBNode>() {
      @Override
      public PBNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBNode> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PBNode> getParserForType() {
      return PARSER;
    }

    @Override
    public PBNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_merkledag_pb_PBLink_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_merkledag_pb_PBLink_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_merkledag_pb_PBNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_merkledag_pb_PBNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017merkledag.proto\022\014merkledag.pb\"3\n\006PBLin" +
      "k\022\014\n\004Hash\030\001 \001(\014\022\014\n\004Name\030\002 \001(\t\022\r\n\005Tsize\030\003" +
      " \001(\004\";\n\006PBNode\022#\n\005Links\030\002 \003(\0132\024.merkleda" +
      "g.pb.PBLink\022\014\n\004Data\030\001 \001(\014"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_merkledag_pb_PBLink_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_merkledag_pb_PBLink_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_merkledag_pb_PBLink_descriptor,
        new String[] { "Hash", "Name", "Tsize", });
    internal_static_merkledag_pb_PBNode_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_merkledag_pb_PBNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_merkledag_pb_PBNode_descriptor,
        new String[] { "Links", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
