// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unixfs.proto

package unixfs.pb;

public final class Unixfs {
  private Unixfs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:unixfs.pb.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .unixfs.pb.Data.DataType Type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required .unixfs.pb.Data.DataType Type = 1;</code>
     * @return The type.
     */
    Data.DataType getType();

    /**
     * <code>optional bytes Data = 2;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>optional bytes Data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional uint64 filesize = 3;</code>
     * @return Whether the filesize field is set.
     */
    boolean hasFilesize();
    /**
     * <code>optional uint64 filesize = 3;</code>
     * @return The filesize.
     */
    long getFilesize();

    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @return A list containing the blocksizes.
     */
    java.util.List<Long> getBlocksizesList();
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @return The count of blocksizes.
     */
    int getBlocksizesCount();
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @param index The index of the element to return.
     * @return The blocksizes at the given index.
     */
    long getBlocksizes(int index);

    /**
     * <code>optional uint64 hashType = 5;</code>
     * @return Whether the hashType field is set.
     */
    boolean hasHashType();
    /**
     * <code>optional uint64 hashType = 5;</code>
     * @return The hashType.
     */
    long getHashType();

    /**
     * <code>optional uint64 fanout = 6;</code>
     * @return Whether the fanout field is set.
     */
    boolean hasFanout();
    /**
     * <code>optional uint64 fanout = 6;</code>
     * @return The fanout.
     */
    long getFanout();
  }
  /**
   * Protobuf type {@code unixfs.pb.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:unixfs.pb.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      type_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      blocksizes_ = emptyLongList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Data();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              DataType value = DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              filesize_ = input.readUInt64();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                blocksizes_ = newLongList();
                mutable_bitField0_ |= 0x00000008;
              }
              blocksizes_.addLong(input.readUInt64());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
                blocksizes_ = newLongList();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                blocksizes_.addLong(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              hashType_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              fanout_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          blocksizes_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Unixfs.internal_static_unixfs_pb_Data_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Unixfs.internal_static_unixfs_pb_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Data.class, Builder.class);
    }

    /**
     * Protobuf enum {@code unixfs.pb.Data.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Raw = 0;</code>
       */
      Raw(0),
      /**
       * <code>Directory = 1;</code>
       */
      Directory(1),
      /**
       * <code>File = 2;</code>
       */
      File(2),
      /**
       * <code>Metadata = 3;</code>
       */
      Metadata(3),
      /**
       * <code>Symlink = 4;</code>
       */
      Symlink(4),
      /**
       * <code>HAMTShard = 5;</code>
       */
      HAMTShard(5),
      ;

      /**
       * <code>Raw = 0;</code>
       */
      public static final int Raw_VALUE = 0;
      /**
       * <code>Directory = 1;</code>
       */
      public static final int Directory_VALUE = 1;
      /**
       * <code>File = 2;</code>
       */
      public static final int File_VALUE = 2;
      /**
       * <code>Metadata = 3;</code>
       */
      public static final int Metadata_VALUE = 3;
      /**
       * <code>Symlink = 4;</code>
       */
      public static final int Symlink_VALUE = 4;
      /**
       * <code>HAMTShard = 5;</code>
       */
      public static final int HAMTShard_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return Raw;
          case 1: return Directory;
          case 2: return File;
          case 3: return Metadata;
          case 4: return Symlink;
          case 5: return HAMTShard;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Data.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:unixfs.pb.Data.DataType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .unixfs.pb.Data.DataType Type = 1;</code>
     * @return Whether the type field is set.
     */
    @Override public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .unixfs.pb.Data.DataType Type = 1;</code>
     * @return The type.
     */
    @Override public DataType getType() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(type_);
      return result == null ? DataType.Raw : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes Data = 2;</code>
     * @return Whether the data field is set.
     */
    @Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes Data = 2;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int FILESIZE_FIELD_NUMBER = 3;
    private long filesize_;
    /**
     * <code>optional uint64 filesize = 3;</code>
     * @return Whether the filesize field is set.
     */
    @Override
    public boolean hasFilesize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 filesize = 3;</code>
     * @return The filesize.
     */
    @Override
    public long getFilesize() {
      return filesize_;
    }

    public static final int BLOCKSIZES_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.LongList blocksizes_;
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @return A list containing the blocksizes.
     */
    @Override
    public java.util.List<Long>
        getBlocksizesList() {
      return blocksizes_;
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @return The count of blocksizes.
     */
    public int getBlocksizesCount() {
      return blocksizes_.size();
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @param index The index of the element to return.
     * @return The blocksizes at the given index.
     */
    public long getBlocksizes(int index) {
      return blocksizes_.getLong(index);
    }

    public static final int HASHTYPE_FIELD_NUMBER = 5;
    private long hashType_;
    /**
     * <code>optional uint64 hashType = 5;</code>
     * @return Whether the hashType field is set.
     */
    @Override
    public boolean hasHashType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 hashType = 5;</code>
     * @return The hashType.
     */
    @Override
    public long getHashType() {
      return hashType_;
    }

    public static final int FANOUT_FIELD_NUMBER = 6;
    private long fanout_;
    /**
     * <code>optional uint64 fanout = 6;</code>
     * @return Whether the fanout field is set.
     */
    @Override
    public boolean hasFanout() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 fanout = 6;</code>
     * @return The fanout.
     */
    @Override
    public long getFanout() {
      return fanout_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, data_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, filesize_);
      }
      for (int i = 0; i < blocksizes_.size(); i++) {
        output.writeUInt64(4, blocksizes_.getLong(i));
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt64(5, hashType_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(6, fanout_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, filesize_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < blocksizes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(blocksizes_.getLong(i));
        }
        size += dataSize;
        size += 1 * getBlocksizesList().size();
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, hashType_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, fanout_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Data)) {
        return super.equals(obj);
      }
      Data other = (Data) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (hasFilesize() != other.hasFilesize()) return false;
      if (hasFilesize()) {
        if (getFilesize()
            != other.getFilesize()) return false;
      }
      if (!getBlocksizesList()
          .equals(other.getBlocksizesList())) return false;
      if (hasHashType() != other.hasHashType()) return false;
      if (hasHashType()) {
        if (getHashType()
            != other.getHashType()) return false;
      }
      if (hasFanout() != other.hasFanout()) return false;
      if (hasFanout()) {
        if (getFanout()
            != other.getFanout()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasFilesize()) {
        hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFilesize());
      }
      if (getBlocksizesCount() > 0) {
        hash = (37 * hash) + BLOCKSIZES_FIELD_NUMBER;
        hash = (53 * hash) + getBlocksizesList().hashCode();
      }
      if (hasHashType()) {
        hash = (37 * hash) + HASHTYPE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getHashType());
      }
      if (hasFanout()) {
        hash = (37 * hash) + FANOUT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFanout());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code unixfs.pb.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:unixfs.pb.Data)
        DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Unixfs.internal_static_unixfs_pb_Data_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Unixfs.internal_static_unixfs_pb_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Data.class, Builder.class);
      }

      // Construct using unixfs.pb.Unixfs.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        filesize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        blocksizes_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000008);
        hashType_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        fanout_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Unixfs.internal_static_unixfs_pb_Data_descriptor;
      }

      @Override
      public Data getDefaultInstanceForType() {
        return Data.getDefaultInstance();
      }

      @Override
      public Data build() {
        Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Data buildPartial() {
        Data result = new Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.filesize_ = filesize_;
          to_bitField0_ |= 0x00000004;
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          blocksizes_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.blocksizes_ = blocksizes_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.hashType_ = hashType_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.fanout_ = fanout_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Data) {
          return mergeFrom((Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Data other) {
        if (other == Data.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasFilesize()) {
          setFilesize(other.getFilesize());
        }
        if (!other.blocksizes_.isEmpty()) {
          if (blocksizes_.isEmpty()) {
            blocksizes_ = other.blocksizes_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureBlocksizesIsMutable();
            blocksizes_.addAll(other.blocksizes_);
          }
          onChanged();
        }
        if (other.hasHashType()) {
          setHashType(other.getHashType());
        }
        if (other.hasFanout()) {
          setFanout(other.getFanout());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .unixfs.pb.Data.DataType Type = 1;</code>
       * @return Whether the type field is set.
       */
      @Override public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .unixfs.pb.Data.DataType Type = 1;</code>
       * @return The type.
       */
      @Override
      public DataType getType() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(type_);
        return result == null ? DataType.Raw : result;
      }
      /**
       * <code>required .unixfs.pb.Data.DataType Type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .unixfs.pb.Data.DataType Type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes Data = 2;</code>
       * @return Whether the data field is set.
       */
      @Override
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes Data = 2;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes Data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes Data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private long filesize_ ;
      /**
       * <code>optional uint64 filesize = 3;</code>
       * @return Whether the filesize field is set.
       */
      @Override
      public boolean hasFilesize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint64 filesize = 3;</code>
       * @return The filesize.
       */
      @Override
      public long getFilesize() {
        return filesize_;
      }
      /**
       * <code>optional uint64 filesize = 3;</code>
       * @param value The filesize to set.
       * @return This builder for chaining.
       */
      public Builder setFilesize(long value) {
        bitField0_ |= 0x00000004;
        filesize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 filesize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilesize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        filesize_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList blocksizes_ = emptyLongList();
      private void ensureBlocksizesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          blocksizes_ = mutableCopy(blocksizes_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @return A list containing the blocksizes.
       */
      public java.util.List<Long>
          getBlocksizesList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(blocksizes_) : blocksizes_;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @return The count of blocksizes.
       */
      public int getBlocksizesCount() {
        return blocksizes_.size();
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @param index The index of the element to return.
       * @return The blocksizes at the given index.
       */
      public long getBlocksizes(int index) {
        return blocksizes_.getLong(index);
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @param index The index to set the value at.
       * @param value The blocksizes to set.
       * @return This builder for chaining.
       */
      public Builder setBlocksizes(
          int index, long value) {
        ensureBlocksizesIsMutable();
        blocksizes_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @param value The blocksizes to add.
       * @return This builder for chaining.
       */
      public Builder addBlocksizes(long value) {
        ensureBlocksizesIsMutable();
        blocksizes_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @param values The blocksizes to add.
       * @return This builder for chaining.
       */
      public Builder addAllBlocksizes(
          Iterable<? extends Long> values) {
        ensureBlocksizesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blocksizes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlocksizes() {
        blocksizes_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private long hashType_ ;
      /**
       * <code>optional uint64 hashType = 5;</code>
       * @return Whether the hashType field is set.
       */
      @Override
      public boolean hasHashType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint64 hashType = 5;</code>
       * @return The hashType.
       */
      @Override
      public long getHashType() {
        return hashType_;
      }
      /**
       * <code>optional uint64 hashType = 5;</code>
       * @param value The hashType to set.
       * @return This builder for chaining.
       */
      public Builder setHashType(long value) {
        bitField0_ |= 0x00000010;
        hashType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 hashType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHashType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hashType_ = 0L;
        onChanged();
        return this;
      }

      private long fanout_ ;
      /**
       * <code>optional uint64 fanout = 6;</code>
       * @return Whether the fanout field is set.
       */
      @Override
      public boolean hasFanout() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint64 fanout = 6;</code>
       * @return The fanout.
       */
      @Override
      public long getFanout() {
        return fanout_;
      }
      /**
       * <code>optional uint64 fanout = 6;</code>
       * @param value The fanout to set.
       * @return This builder for chaining.
       */
      public Builder setFanout(long value) {
        bitField0_ |= 0x00000020;
        fanout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 fanout = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFanout() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fanout_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:unixfs.pb.Data)
    }

    // @@protoc_insertion_point(class_scope:unixfs.pb.Data)
    private static final Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Data();
    }

    public static Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @Override
    public Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:unixfs.pb.Metadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string MimeType = 1;</code>
     * @return Whether the mimeType field is set.
     */
    boolean hasMimeType();
    /**
     * <code>optional string MimeType = 1;</code>
     * @return The mimeType.
     */
    String getMimeType();
    /**
     * <code>optional string MimeType = 1;</code>
     * @return The bytes for mimeType.
     */
    com.google.protobuf.ByteString
        getMimeTypeBytes();
  }
  /**
   * Protobuf type {@code unixfs.pb.Metadata}
   */
  public static final class Metadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:unixfs.pb.Metadata)
      MetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Metadata.newBuilder() to construct.
    private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Metadata() {
      mimeType_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Metadata();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Metadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              mimeType_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Unixfs.internal_static_unixfs_pb_Metadata_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Unixfs.internal_static_unixfs_pb_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Metadata.class, Builder.class);
    }

    private int bitField0_;
    public static final int MIMETYPE_FIELD_NUMBER = 1;
    private volatile Object mimeType_;
    /**
     * <code>optional string MimeType = 1;</code>
     * @return Whether the mimeType field is set.
     */
    @Override
    public boolean hasMimeType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string MimeType = 1;</code>
     * @return The mimeType.
     */
    @Override
    public String getMimeType() {
      Object ref = mimeType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mimeType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string MimeType = 1;</code>
     * @return The bytes for mimeType.
     */
    @Override
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      Object ref = mimeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mimeType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mimeType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Metadata)) {
        return super.equals(obj);
      }
      Metadata other = (Metadata) obj;

      if (hasMimeType() != other.hasMimeType()) return false;
      if (hasMimeType()) {
        if (!getMimeType()
            .equals(other.getMimeType())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMimeType()) {
        hash = (37 * hash) + MIMETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMimeType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Metadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Metadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Metadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code unixfs.pb.Metadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:unixfs.pb.Metadata)
        MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Unixfs.internal_static_unixfs_pb_Metadata_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Unixfs.internal_static_unixfs_pb_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Metadata.class, Builder.class);
      }

      // Construct using unixfs.pb.Unixfs.Metadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        mimeType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Unixfs.internal_static_unixfs_pb_Metadata_descriptor;
      }

      @Override
      public Metadata getDefaultInstanceForType() {
        return Metadata.getDefaultInstance();
      }

      @Override
      public Metadata build() {
        Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Metadata buildPartial() {
        Metadata result = new Metadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mimeType_ = mimeType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Metadata) {
          return mergeFrom((Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Metadata other) {
        if (other == Metadata.getDefaultInstance()) return this;
        if (other.hasMimeType()) {
          bitField0_ |= 0x00000001;
          mimeType_ = other.mimeType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Metadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Metadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object mimeType_ = "";
      /**
       * <code>optional string MimeType = 1;</code>
       * @return Whether the mimeType field is set.
       */
      public boolean hasMimeType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @return The mimeType.
       */
      public String getMimeType() {
        Object ref = mimeType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mimeType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @return The bytes for mimeType.
       */
      public com.google.protobuf.ByteString
          getMimeTypeBytes() {
        Object ref = mimeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mimeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @param value The mimeType to set.
       * @return This builder for chaining.
       */
      public Builder setMimeType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mimeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMimeType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mimeType_ = getDefaultInstance().getMimeType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @param value The bytes for mimeType to set.
       * @return This builder for chaining.
       */
      public Builder setMimeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mimeType_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:unixfs.pb.Metadata)
    }

    // @@protoc_insertion_point(class_scope:unixfs.pb.Metadata)
    private static final Metadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Metadata();
    }

    public static Metadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Metadata>
        PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
      @Override
      public Metadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Metadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Metadata> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Metadata> getParserForType() {
      return PARSER;
    }

    @Override
    public Metadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_unixfs_pb_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_unixfs_pb_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_unixfs_pb_Metadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_unixfs_pb_Metadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014unixfs.proto\022\tunixfs.pb\"\334\001\n\004Data\022&\n\004Ty" +
      "pe\030\001 \002(\0162\030.unixfs.pb.Data.DataType\022\014\n\004Da" +
      "ta\030\002 \001(\014\022\020\n\010filesize\030\003 \001(\004\022\022\n\nblocksizes" +
      "\030\004 \003(\004\022\020\n\010hashType\030\005 \001(\004\022\016\n\006fanout\030\006 \001(\004" +
      "\"V\n\010DataType\022\007\n\003Raw\020\000\022\r\n\tDirectory\020\001\022\010\n\004" +
      "File\020\002\022\014\n\010Metadata\020\003\022\013\n\007Symlink\020\004\022\r\n\tHAM" +
      "TShard\020\005\"\034\n\010Metadata\022\020\n\010MimeType\030\001 \001(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_unixfs_pb_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_unixfs_pb_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_unixfs_pb_Data_descriptor,
        new String[] { "Type", "Data", "Filesize", "Blocksizes", "HashType", "Fanout", });
    internal_static_unixfs_pb_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_unixfs_pb_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_unixfs_pb_Metadata_descriptor,
        new String[] { "MimeType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
