// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipns.proto

package ipns.pb;

public final class Ipns {
  private Ipns() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IpnsEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ipns.pb.IpnsEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes value = 1;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 1;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>required bytes signature = 2;</code>
     * @return Whether the signature field is set.
     */
    boolean hasSignature();
    /**
     * <code>required bytes signature = 2;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>optional .ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
     * @return Whether the validityType field is set.
     */
    boolean hasValidityType();
    /**
     * <code>optional .ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
     * @return The validityType.
     */
    IpnsEntry.ValidityType getValidityType();

    /**
     * <code>optional bytes validity = 4;</code>
     * @return Whether the validity field is set.
     */
    boolean hasValidity();
    /**
     * <code>optional bytes validity = 4;</code>
     * @return The validity.
     */
    com.google.protobuf.ByteString getValidity();

    /**
     * <code>optional uint64 sequence = 5;</code>
     * @return Whether the sequence field is set.
     */
    boolean hasSequence();
    /**
     * <code>optional uint64 sequence = 5;</code>
     * @return The sequence.
     */
    long getSequence();

    /**
     * <code>optional uint64 ttl = 6;</code>
     * @return Whether the ttl field is set.
     */
    boolean hasTtl();
    /**
     * <code>optional uint64 ttl = 6;</code>
     * @return The ttl.
     */
    long getTtl();

    /**
     * <pre>
     * in order for nodes to properly validate a record upon receipt, they need the public
     * key associated with it. For old RSA keys, its easiest if we just send this as part of
     * the record itself. For newer ed25519 keys, the public key can be embedded in the
     * peerID, making this field unnecessary.
     * </pre>
     *
     * <code>optional bytes pubKey = 7;</code>
     * @return Whether the pubKey field is set.
     */
    boolean hasPubKey();
    /**
     * <pre>
     * in order for nodes to properly validate a record upon receipt, they need the public
     * key associated with it. For old RSA keys, its easiest if we just send this as part of
     * the record itself. For newer ed25519 keys, the public key can be embedded in the
     * peerID, making this field unnecessary.
     * </pre>
     *
     * <code>optional bytes pubKey = 7;</code>
     * @return The pubKey.
     */
    com.google.protobuf.ByteString getPubKey();
  }
  /**
   * Protobuf type {@code ipns.pb.IpnsEntry}
   */
  public static final class IpnsEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ipns.pb.IpnsEntry)
      IpnsEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IpnsEntry.newBuilder() to construct.
    private IpnsEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IpnsEntry() {
      value_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      validityType_ = 0;
      validity_ = com.google.protobuf.ByteString.EMPTY;
      pubKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new IpnsEntry();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IpnsEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              value_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              signature_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              ValidityType value = ValidityType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                validityType_ = rawValue;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              validity_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sequence_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              ttl_ = input.readUInt64();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              pubKey_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Ipns.internal_static_ipns_pb_IpnsEntry_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Ipns.internal_static_ipns_pb_IpnsEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IpnsEntry.class, Builder.class);
    }

    /**
     * Protobuf enum {@code ipns.pb.IpnsEntry.ValidityType}
     */
    public enum ValidityType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * setting an EOL says "this record is valid until..."
       * </pre>
       *
       * <code>EOL = 0;</code>
       */
      EOL(0),
      ;

      /**
       * <pre>
       * setting an EOL says "this record is valid until..."
       * </pre>
       *
       * <code>EOL = 0;</code>
       */
      public static final int EOL_VALUE = 0;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ValidityType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ValidityType forNumber(int value) {
        switch (value) {
          case 0: return EOL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ValidityType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ValidityType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValidityType>() {
              public ValidityType findValueByNumber(int number) {
                return ValidityType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return IpnsEntry.getDescriptor().getEnumTypes().get(0);
      }

      private static final ValidityType[] VALUES = values();

      public static ValidityType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ValidityType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ipns.pb.IpnsEntry.ValidityType)
    }

    private int bitField0_;
    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 1;</code>
     * @return Whether the value field is set.
     */
    @Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bytes value = 1;</code>
     * @return The value.
     */
    @Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>required bytes signature = 2;</code>
     * @return Whether the signature field is set.
     */
    @Override
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bytes signature = 2;</code>
     * @return The signature.
     */
    @Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int VALIDITYTYPE_FIELD_NUMBER = 3;
    private int validityType_;
    /**
     * <code>optional .ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
     * @return Whether the validityType field is set.
     */
    @Override public boolean hasValidityType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
     * @return The validityType.
     */
    @Override public ValidityType getValidityType() {
      @SuppressWarnings("deprecation")
      ValidityType result = ValidityType.valueOf(validityType_);
      return result == null ? ValidityType.EOL : result;
    }

    public static final int VALIDITY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString validity_;
    /**
     * <code>optional bytes validity = 4;</code>
     * @return Whether the validity field is set.
     */
    @Override
    public boolean hasValidity() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes validity = 4;</code>
     * @return The validity.
     */
    @Override
    public com.google.protobuf.ByteString getValidity() {
      return validity_;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 5;
    private long sequence_;
    /**
     * <code>optional uint64 sequence = 5;</code>
     * @return Whether the sequence field is set.
     */
    @Override
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 sequence = 5;</code>
     * @return The sequence.
     */
    @Override
    public long getSequence() {
      return sequence_;
    }

    public static final int TTL_FIELD_NUMBER = 6;
    private long ttl_;
    /**
     * <code>optional uint64 ttl = 6;</code>
     * @return Whether the ttl field is set.
     */
    @Override
    public boolean hasTtl() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint64 ttl = 6;</code>
     * @return The ttl.
     */
    @Override
    public long getTtl() {
      return ttl_;
    }

    public static final int PUBKEY_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString pubKey_;
    /**
     * <pre>
     * in order for nodes to properly validate a record upon receipt, they need the public
     * key associated with it. For old RSA keys, its easiest if we just send this as part of
     * the record itself. For newer ed25519 keys, the public key can be embedded in the
     * peerID, making this field unnecessary.
     * </pre>
     *
     * <code>optional bytes pubKey = 7;</code>
     * @return Whether the pubKey field is set.
     */
    @Override
    public boolean hasPubKey() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * in order for nodes to properly validate a record upon receipt, they need the public
     * key associated with it. For old RSA keys, its easiest if we just send this as part of
     * the record itself. For newer ed25519 keys, the public key can be embedded in the
     * peerID, making this field unnecessary.
     * </pre>
     *
     * <code>optional bytes pubKey = 7;</code>
     * @return The pubKey.
     */
    @Override
    public com.google.protobuf.ByteString getPubKey() {
      return pubKey_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, signature_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, validityType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, validity_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(5, sequence_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt64(6, ttl_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBytes(7, pubKey_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, validityType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, validity_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, sequence_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, ttl_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, pubKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IpnsEntry)) {
        return super.equals(obj);
      }
      IpnsEntry other = (IpnsEntry) obj;

      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (hasSignature() != other.hasSignature()) return false;
      if (hasSignature()) {
        if (!getSignature()
            .equals(other.getSignature())) return false;
      }
      if (hasValidityType() != other.hasValidityType()) return false;
      if (hasValidityType()) {
        if (validityType_ != other.validityType_) return false;
      }
      if (hasValidity() != other.hasValidity()) return false;
      if (hasValidity()) {
        if (!getValidity()
            .equals(other.getValidity())) return false;
      }
      if (hasSequence() != other.hasSequence()) return false;
      if (hasSequence()) {
        if (getSequence()
            != other.getSequence()) return false;
      }
      if (hasTtl() != other.hasTtl()) return false;
      if (hasTtl()) {
        if (getTtl()
            != other.getTtl()) return false;
      }
      if (hasPubKey() != other.hasPubKey()) return false;
      if (hasPubKey()) {
        if (!getPubKey()
            .equals(other.getPubKey())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (hasValidityType()) {
        hash = (37 * hash) + VALIDITYTYPE_FIELD_NUMBER;
        hash = (53 * hash) + validityType_;
      }
      if (hasValidity()) {
        hash = (37 * hash) + VALIDITY_FIELD_NUMBER;
        hash = (53 * hash) + getValidity().hashCode();
      }
      if (hasSequence()) {
        hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSequence());
      }
      if (hasTtl()) {
        hash = (37 * hash) + TTL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTtl());
      }
      if (hasPubKey()) {
        hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubKey().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IpnsEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IpnsEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IpnsEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IpnsEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IpnsEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IpnsEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IpnsEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IpnsEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IpnsEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IpnsEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IpnsEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IpnsEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IpnsEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ipns.pb.IpnsEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ipns.pb.IpnsEntry)
        IpnsEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Ipns.internal_static_ipns_pb_IpnsEntry_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Ipns.internal_static_ipns_pb_IpnsEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IpnsEntry.class, Builder.class);
      }

      // Construct using ipns.pb.Ipns.IpnsEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        validityType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        validity_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        sequence_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        ttl_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        pubKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Ipns.internal_static_ipns_pb_IpnsEntry_descriptor;
      }

      @Override
      public IpnsEntry getDefaultInstanceForType() {
        return IpnsEntry.getDefaultInstance();
      }

      @Override
      public IpnsEntry build() {
        IpnsEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public IpnsEntry buildPartial() {
        IpnsEntry result = new IpnsEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.validityType_ = validityType_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.validity_ = validity_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sequence_ = sequence_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.ttl_ = ttl_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.pubKey_ = pubKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IpnsEntry) {
          return mergeFrom((IpnsEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IpnsEntry other) {
        if (other == IpnsEntry.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        if (other.hasValidityType()) {
          setValidityType(other.getValidityType());
        }
        if (other.hasValidity()) {
          setValidity(other.getValidity());
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasTtl()) {
          setTtl(other.getTtl());
        }
        if (other.hasPubKey()) {
          setPubKey(other.getPubKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasValue()) {
          return false;
        }
        if (!hasSignature()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IpnsEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IpnsEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 1;</code>
       * @return Whether the value field is set.
       */
      @Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required bytes value = 1;</code>
       * @return The value.
       */
      @Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes signature = 2;</code>
       * @return Whether the signature field is set.
       */
      @Override
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required bytes signature = 2;</code>
       * @return The signature.
       */
      @Override
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>required bytes signature = 2;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes signature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private int validityType_ = 0;
      /**
       * <code>optional .ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
       * @return Whether the validityType field is set.
       */
      @Override public boolean hasValidityType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
       * @return The validityType.
       */
      @Override
      public ValidityType getValidityType() {
        @SuppressWarnings("deprecation")
        ValidityType result = ValidityType.valueOf(validityType_);
        return result == null ? ValidityType.EOL : result;
      }
      /**
       * <code>optional .ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
       * @param value The validityType to set.
       * @return This builder for chaining.
       */
      public Builder setValidityType(ValidityType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        validityType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValidityType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        validityType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString validity_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes validity = 4;</code>
       * @return Whether the validity field is set.
       */
      @Override
      public boolean hasValidity() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes validity = 4;</code>
       * @return The validity.
       */
      @Override
      public com.google.protobuf.ByteString getValidity() {
        return validity_;
      }
      /**
       * <code>optional bytes validity = 4;</code>
       * @param value The validity to set.
       * @return This builder for chaining.
       */
      public Builder setValidity(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        validity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes validity = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValidity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        validity_ = getDefaultInstance().getValidity();
        onChanged();
        return this;
      }

      private long sequence_ ;
      /**
       * <code>optional uint64 sequence = 5;</code>
       * @return Whether the sequence field is set.
       */
      @Override
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint64 sequence = 5;</code>
       * @return The sequence.
       */
      @Override
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>optional uint64 sequence = 5;</code>
       * @param value The sequence to set.
       * @return This builder for chaining.
       */
      public Builder setSequence(long value) {
        bitField0_ |= 0x00000010;
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sequence = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private long ttl_ ;
      /**
       * <code>optional uint64 ttl = 6;</code>
       * @return Whether the ttl field is set.
       */
      @Override
      public boolean hasTtl() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint64 ttl = 6;</code>
       * @return The ttl.
       */
      @Override
      public long getTtl() {
        return ttl_;
      }
      /**
       * <code>optional uint64 ttl = 6;</code>
       * @param value The ttl to set.
       * @return This builder for chaining.
       */
      public Builder setTtl(long value) {
        bitField0_ |= 0x00000020;
        ttl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ttl = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTtl() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ttl_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pubKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * in order for nodes to properly validate a record upon receipt, they need the public
       * key associated with it. For old RSA keys, its easiest if we just send this as part of
       * the record itself. For newer ed25519 keys, the public key can be embedded in the
       * peerID, making this field unnecessary.
       * </pre>
       *
       * <code>optional bytes pubKey = 7;</code>
       * @return Whether the pubKey field is set.
       */
      @Override
      public boolean hasPubKey() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * in order for nodes to properly validate a record upon receipt, they need the public
       * key associated with it. For old RSA keys, its easiest if we just send this as part of
       * the record itself. For newer ed25519 keys, the public key can be embedded in the
       * peerID, making this field unnecessary.
       * </pre>
       *
       * <code>optional bytes pubKey = 7;</code>
       * @return The pubKey.
       */
      @Override
      public com.google.protobuf.ByteString getPubKey() {
        return pubKey_;
      }
      /**
       * <pre>
       * in order for nodes to properly validate a record upon receipt, they need the public
       * key associated with it. For old RSA keys, its easiest if we just send this as part of
       * the record itself. For newer ed25519 keys, the public key can be embedded in the
       * peerID, making this field unnecessary.
       * </pre>
       *
       * <code>optional bytes pubKey = 7;</code>
       * @param value The pubKey to set.
       * @return This builder for chaining.
       */
      public Builder setPubKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        pubKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * in order for nodes to properly validate a record upon receipt, they need the public
       * key associated with it. For old RSA keys, its easiest if we just send this as part of
       * the record itself. For newer ed25519 keys, the public key can be embedded in the
       * peerID, making this field unnecessary.
       * </pre>
       *
       * <code>optional bytes pubKey = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPubKey() {
        bitField0_ = (bitField0_ & ~0x00000040);
        pubKey_ = getDefaultInstance().getPubKey();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ipns.pb.IpnsEntry)
    }

    // @@protoc_insertion_point(class_scope:ipns.pb.IpnsEntry)
    private static final IpnsEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IpnsEntry();
    }

    public static IpnsEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<IpnsEntry>
        PARSER = new com.google.protobuf.AbstractParser<IpnsEntry>() {
      @Override
      public IpnsEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IpnsEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IpnsEntry> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<IpnsEntry> getParserForType() {
      return PARSER;
    }

    @Override
    public IpnsEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ipns_pb_IpnsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ipns_pb_IpnsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nipns.proto\022\007ipns.pb\"\276\001\n\tIpnsEntry\022\r\n\005v" +
      "alue\030\001 \002(\014\022\021\n\tsignature\030\002 \002(\014\0225\n\014validit" +
      "yType\030\003 \001(\0162\037.ipns.pb.IpnsEntry.Validity" +
      "Type\022\020\n\010validity\030\004 \001(\014\022\020\n\010sequence\030\005 \001(\004" +
      "\022\013\n\003ttl\030\006 \001(\004\022\016\n\006pubKey\030\007 \001(\014\"\027\n\014Validit" +
      "yType\022\007\n\003EOL\020\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ipns_pb_IpnsEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ipns_pb_IpnsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ipns_pb_IpnsEntry_descriptor,
        new String[] { "Value", "Signature", "ValidityType", "Validity", "Sequence", "Ttl", "PubKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
