// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identify.proto

package identify.pb;

public final class IdentifyOuterClass {
  private IdentifyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IdentifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:identify.pb.Identify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     * @return Whether the protocolVersion field is set.
     */
    boolean hasProtocolVersion();
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     * @return The protocolVersion.
     */
    String getProtocolVersion();
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     * @return The bytes for protocolVersion.
     */
    com.google.protobuf.ByteString
        getProtocolVersionBytes();

    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     * @return Whether the agentVersion field is set.
     */
    boolean hasAgentVersion();
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     * @return The agentVersion.
     */
    String getAgentVersion();
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     * @return The bytes for agentVersion.
     */
    com.google.protobuf.ByteString
        getAgentVersionBytes();

    /**
     * <pre>
     * publicKey is this node's public key (which also gives its node.ID)
     * - may not need to be sent, as secure channel implies it has been sent.
     * - then again, if we change / disable secure channel, may still want it.
     * </pre>
     *
     * <code>optional bytes publicKey = 1;</code>
     * @return Whether the publicKey field is set.
     */
    boolean hasPublicKey();
    /**
     * <pre>
     * publicKey is this node's public key (which also gives its node.ID)
     * - may not need to be sent, as secure channel implies it has been sent.
     * - then again, if we change / disable secure channel, may still want it.
     * </pre>
     *
     * <code>optional bytes publicKey = 1;</code>
     * @return The publicKey.
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     * @return A list containing the listenAddrs.
     */
    java.util.List<com.google.protobuf.ByteString> getListenAddrsList();
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     * @return The count of listenAddrs.
     */
    int getListenAddrsCount();
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     * @param index The index of the element to return.
     * @return The listenAddrs at the given index.
     */
    com.google.protobuf.ByteString getListenAddrs(int index);

    /**
     * <pre>
     * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
     * this is useful information to convey to the other side, as it helps the remote endpoint
     * determine whether its connection to the local peer goes through NAT.
     * </pre>
     *
     * <code>optional bytes observedAddr = 4;</code>
     * @return Whether the observedAddr field is set.
     */
    boolean hasObservedAddr();
    /**
     * <pre>
     * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
     * this is useful information to convey to the other side, as it helps the remote endpoint
     * determine whether its connection to the local peer goes through NAT.
     * </pre>
     *
     * <code>optional bytes observedAddr = 4;</code>
     * @return The observedAddr.
     */
    com.google.protobuf.ByteString getObservedAddr();

    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     * @return A list containing the protocols.
     */
    java.util.List<String>
        getProtocolsList();
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     * @return The count of protocols.
     */
    int getProtocolsCount();
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     * @param index The index of the element to return.
     * @return The protocols at the given index.
     */
    String getProtocols(int index);
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the protocols at the given index.
     */
    com.google.protobuf.ByteString
        getProtocolsBytes(int index);
  }
  /**
   * Protobuf type {@code identify.pb.Identify}
   */
  public static final class Identify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:identify.pb.Identify)
      IdentifyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Identify.newBuilder() to construct.
    private Identify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Identify() {
      protocolVersion_ = "";
      agentVersion_ = "";
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      listenAddrs_ = java.util.Collections.emptyList();
      observedAddr_ = com.google.protobuf.ByteString.EMPTY;
      protocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Identify();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Identify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000004;
              publicKey_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                listenAddrs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              listenAddrs_.add(input.readBytes());
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                protocols_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              protocols_.add(bs);
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              observedAddr_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              protocolVersion_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              agentVersion_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          listenAddrs_ = java.util.Collections.unmodifiableList(listenAddrs_); // C
        }
        if (((mutable_bitField0_ & 0x00000020) != 0)) {
          protocols_ = protocols_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IdentifyOuterClass.internal_static_identify_pb_Identify_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IdentifyOuterClass.internal_static_identify_pb_Identify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Identify.class, Builder.class);
    }

    private int bitField0_;
    public static final int PROTOCOLVERSION_FIELD_NUMBER = 5;
    private volatile Object protocolVersion_;
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     * @return Whether the protocolVersion field is set.
     */
    @Override
    public boolean hasProtocolVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     * @return The protocolVersion.
     */
    @Override
    public String getProtocolVersion() {
      Object ref = protocolVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          protocolVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     * @return The bytes for protocolVersion.
     */
    @Override
    public com.google.protobuf.ByteString
        getProtocolVersionBytes() {
      Object ref = protocolVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        protocolVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGENTVERSION_FIELD_NUMBER = 6;
    private volatile Object agentVersion_;
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     * @return Whether the agentVersion field is set.
     */
    @Override
    public boolean hasAgentVersion() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     * @return The agentVersion.
     */
    @Override
    public String getAgentVersion() {
      Object ref = agentVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          agentVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     * @return The bytes for agentVersion.
     */
    @Override
    public com.google.protobuf.ByteString
        getAgentVersionBytes() {
      Object ref = agentVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        agentVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <pre>
     * publicKey is this node's public key (which also gives its node.ID)
     * - may not need to be sent, as secure channel implies it has been sent.
     * - then again, if we change / disable secure channel, may still want it.
     * </pre>
     *
     * <code>optional bytes publicKey = 1;</code>
     * @return Whether the publicKey field is set.
     */
    @Override
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * publicKey is this node's public key (which also gives its node.ID)
     * - may not need to be sent, as secure channel implies it has been sent.
     * - then again, if we change / disable secure channel, may still want it.
     * </pre>
     *
     * <code>optional bytes publicKey = 1;</code>
     * @return The publicKey.
     */
    @Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int LISTENADDRS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> listenAddrs_;
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     * @return A list containing the listenAddrs.
     */
    @Override
    public java.util.List<com.google.protobuf.ByteString>
        getListenAddrsList() {
      return listenAddrs_;
    }
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     * @return The count of listenAddrs.
     */
    public int getListenAddrsCount() {
      return listenAddrs_.size();
    }
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     * @param index The index of the element to return.
     * @return The listenAddrs at the given index.
     */
    public com.google.protobuf.ByteString getListenAddrs(int index) {
      return listenAddrs_.get(index);
    }

    public static final int OBSERVEDADDR_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString observedAddr_;
    /**
     * <pre>
     * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
     * this is useful information to convey to the other side, as it helps the remote endpoint
     * determine whether its connection to the local peer goes through NAT.
     * </pre>
     *
     * <code>optional bytes observedAddr = 4;</code>
     * @return Whether the observedAddr field is set.
     */
    @Override
    public boolean hasObservedAddr() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
     * this is useful information to convey to the other side, as it helps the remote endpoint
     * determine whether its connection to the local peer goes through NAT.
     * </pre>
     *
     * <code>optional bytes observedAddr = 4;</code>
     * @return The observedAddr.
     */
    @Override
    public com.google.protobuf.ByteString getObservedAddr() {
      return observedAddr_;
    }

    public static final int PROTOCOLS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList protocols_;
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     * @return A list containing the protocols.
     */
    public com.google.protobuf.ProtocolStringList
        getProtocolsList() {
      return protocols_;
    }
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     * @return The count of protocols.
     */
    public int getProtocolsCount() {
      return protocols_.size();
    }
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     * @param index The index of the element to return.
     * @return The protocols at the given index.
     */
    public String getProtocols(int index) {
      return protocols_.get(index);
    }
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the protocols at the given index.
     */
    public com.google.protobuf.ByteString
        getProtocolsBytes(int index) {
      return protocols_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(1, publicKey_);
      }
      for (int i = 0; i < listenAddrs_.size(); i++) {
        output.writeBytes(2, listenAddrs_.get(i));
      }
      for (int i = 0; i < protocols_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, protocols_.getRaw(i));
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, observedAddr_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, agentVersion_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, publicKey_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < listenAddrs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(listenAddrs_.get(i));
        }
        size += dataSize;
        size += 1 * getListenAddrsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < protocols_.size(); i++) {
          dataSize += computeStringSizeNoTag(protocols_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProtocolsList().size();
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, observedAddr_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, agentVersion_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Identify)) {
        return super.equals(obj);
      }
      Identify other = (Identify) obj;

      if (hasProtocolVersion() != other.hasProtocolVersion()) return false;
      if (hasProtocolVersion()) {
        if (!getProtocolVersion()
            .equals(other.getProtocolVersion())) return false;
      }
      if (hasAgentVersion() != other.hasAgentVersion()) return false;
      if (hasAgentVersion()) {
        if (!getAgentVersion()
            .equals(other.getAgentVersion())) return false;
      }
      if (hasPublicKey() != other.hasPublicKey()) return false;
      if (hasPublicKey()) {
        if (!getPublicKey()
            .equals(other.getPublicKey())) return false;
      }
      if (!getListenAddrsList()
          .equals(other.getListenAddrsList())) return false;
      if (hasObservedAddr() != other.hasObservedAddr()) return false;
      if (hasObservedAddr()) {
        if (!getObservedAddr()
            .equals(other.getObservedAddr())) return false;
      }
      if (!getProtocolsList()
          .equals(other.getProtocolsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProtocolVersion()) {
        hash = (37 * hash) + PROTOCOLVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolVersion().hashCode();
      }
      if (hasAgentVersion()) {
        hash = (37 * hash) + AGENTVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getAgentVersion().hashCode();
      }
      if (hasPublicKey()) {
        hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPublicKey().hashCode();
      }
      if (getListenAddrsCount() > 0) {
        hash = (37 * hash) + LISTENADDRS_FIELD_NUMBER;
        hash = (53 * hash) + getListenAddrsList().hashCode();
      }
      if (hasObservedAddr()) {
        hash = (37 * hash) + OBSERVEDADDR_FIELD_NUMBER;
        hash = (53 * hash) + getObservedAddr().hashCode();
      }
      if (getProtocolsCount() > 0) {
        hash = (37 * hash) + PROTOCOLS_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Identify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Identify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Identify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Identify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Identify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Identify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Identify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Identify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Identify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Identify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Identify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Identify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Identify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code identify.pb.Identify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:identify.pb.Identify)
        IdentifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IdentifyOuterClass.internal_static_identify_pb_Identify_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IdentifyOuterClass.internal_static_identify_pb_Identify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Identify.class, Builder.class);
      }

      // Construct using identify.pb.IdentifyOuterClass.Identify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        protocolVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        agentVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        listenAddrs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        observedAddr_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        protocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IdentifyOuterClass.internal_static_identify_pb_Identify_descriptor;
      }

      @Override
      public Identify getDefaultInstanceForType() {
        return Identify.getDefaultInstance();
      }

      @Override
      public Identify build() {
        Identify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Identify buildPartial() {
        Identify result = new Identify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protocolVersion_ = protocolVersion_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.agentVersion_ = agentVersion_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.publicKey_ = publicKey_;
        if (((bitField0_ & 0x00000008) != 0)) {
          listenAddrs_ = java.util.Collections.unmodifiableList(listenAddrs_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.listenAddrs_ = listenAddrs_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.observedAddr_ = observedAddr_;
        if (((bitField0_ & 0x00000020) != 0)) {
          protocols_ = protocols_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.protocols_ = protocols_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Identify) {
          return mergeFrom((Identify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Identify other) {
        if (other == Identify.getDefaultInstance()) return this;
        if (other.hasProtocolVersion()) {
          bitField0_ |= 0x00000001;
          protocolVersion_ = other.protocolVersion_;
          onChanged();
        }
        if (other.hasAgentVersion()) {
          bitField0_ |= 0x00000002;
          agentVersion_ = other.agentVersion_;
          onChanged();
        }
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        if (!other.listenAddrs_.isEmpty()) {
          if (listenAddrs_.isEmpty()) {
            listenAddrs_ = other.listenAddrs_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureListenAddrsIsMutable();
            listenAddrs_.addAll(other.listenAddrs_);
          }
          onChanged();
        }
        if (other.hasObservedAddr()) {
          setObservedAddr(other.getObservedAddr());
        }
        if (!other.protocols_.isEmpty()) {
          if (protocols_.isEmpty()) {
            protocols_ = other.protocols_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureProtocolsIsMutable();
            protocols_.addAll(other.protocols_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Identify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Identify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object protocolVersion_ = "";
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       * @return Whether the protocolVersion field is set.
       */
      public boolean hasProtocolVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       * @return The protocolVersion.
       */
      public String getProtocolVersion() {
        Object ref = protocolVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            protocolVersion_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       * @return The bytes for protocolVersion.
       */
      public com.google.protobuf.ByteString
          getProtocolVersionBytes() {
        Object ref = protocolVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          protocolVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       * @param value The protocolVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        protocolVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolVersion_ = getDefaultInstance().getProtocolVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       * @param value The bytes for protocolVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        protocolVersion_ = value;
        onChanged();
        return this;
      }

      private Object agentVersion_ = "";
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       * @return Whether the agentVersion field is set.
       */
      public boolean hasAgentVersion() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       * @return The agentVersion.
       */
      public String getAgentVersion() {
        Object ref = agentVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            agentVersion_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       * @return The bytes for agentVersion.
       */
      public com.google.protobuf.ByteString
          getAgentVersionBytes() {
        Object ref = agentVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          agentVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       * @param value The agentVersion to set.
       * @return This builder for chaining.
       */
      public Builder setAgentVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        agentVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgentVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        agentVersion_ = getDefaultInstance().getAgentVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       * @param value The bytes for agentVersion to set.
       * @return This builder for chaining.
       */
      public Builder setAgentVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        agentVersion_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * publicKey is this node's public key (which also gives its node.ID)
       * - may not need to be sent, as secure channel implies it has been sent.
       * - then again, if we change / disable secure channel, may still want it.
       * </pre>
       *
       * <code>optional bytes publicKey = 1;</code>
       * @return Whether the publicKey field is set.
       */
      @Override
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * publicKey is this node's public key (which also gives its node.ID)
       * - may not need to be sent, as secure channel implies it has been sent.
       * - then again, if we change / disable secure channel, may still want it.
       * </pre>
       *
       * <code>optional bytes publicKey = 1;</code>
       * @return The publicKey.
       */
      @Override
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <pre>
       * publicKey is this node's public key (which also gives its node.ID)
       * - may not need to be sent, as secure channel implies it has been sent.
       * - then again, if we change / disable secure channel, may still want it.
       * </pre>
       *
       * <code>optional bytes publicKey = 1;</code>
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * publicKey is this node's public key (which also gives its node.ID)
       * - may not need to be sent, as secure channel implies it has been sent.
       * - then again, if we change / disable secure channel, may still want it.
       * </pre>
       *
       * <code>optional bytes publicKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> listenAddrs_ = java.util.Collections.emptyList();
      private void ensureListenAddrsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          listenAddrs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(listenAddrs_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       * @return A list containing the listenAddrs.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getListenAddrsList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(listenAddrs_) : listenAddrs_;
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       * @return The count of listenAddrs.
       */
      public int getListenAddrsCount() {
        return listenAddrs_.size();
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       * @param index The index of the element to return.
       * @return The listenAddrs at the given index.
       */
      public com.google.protobuf.ByteString getListenAddrs(int index) {
        return listenAddrs_.get(index);
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       * @param index The index to set the value at.
       * @param value The listenAddrs to set.
       * @return This builder for chaining.
       */
      public Builder setListenAddrs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListenAddrsIsMutable();
        listenAddrs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       * @param value The listenAddrs to add.
       * @return This builder for chaining.
       */
      public Builder addListenAddrs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListenAddrsIsMutable();
        listenAddrs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       * @param values The listenAddrs to add.
       * @return This builder for chaining.
       */
      public Builder addAllListenAddrs(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureListenAddrsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listenAddrs_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearListenAddrs() {
        listenAddrs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString observedAddr_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
       * this is useful information to convey to the other side, as it helps the remote endpoint
       * determine whether its connection to the local peer goes through NAT.
       * </pre>
       *
       * <code>optional bytes observedAddr = 4;</code>
       * @return Whether the observedAddr field is set.
       */
      @Override
      public boolean hasObservedAddr() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
       * this is useful information to convey to the other side, as it helps the remote endpoint
       * determine whether its connection to the local peer goes through NAT.
       * </pre>
       *
       * <code>optional bytes observedAddr = 4;</code>
       * @return The observedAddr.
       */
      @Override
      public com.google.protobuf.ByteString getObservedAddr() {
        return observedAddr_;
      }
      /**
       * <pre>
       * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
       * this is useful information to convey to the other side, as it helps the remote endpoint
       * determine whether its connection to the local peer goes through NAT.
       * </pre>
       *
       * <code>optional bytes observedAddr = 4;</code>
       * @param value The observedAddr to set.
       * @return This builder for chaining.
       */
      public Builder setObservedAddr(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        observedAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
       * this is useful information to convey to the other side, as it helps the remote endpoint
       * determine whether its connection to the local peer goes through NAT.
       * </pre>
       *
       * <code>optional bytes observedAddr = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearObservedAddr() {
        bitField0_ = (bitField0_ & ~0x00000010);
        observedAddr_ = getDefaultInstance().getObservedAddr();
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList protocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureProtocolsIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          protocols_ = new com.google.protobuf.LazyStringArrayList(protocols_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       * @return A list containing the protocols.
       */
      public com.google.protobuf.ProtocolStringList
          getProtocolsList() {
        return protocols_.getUnmodifiableView();
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       * @return The count of protocols.
       */
      public int getProtocolsCount() {
        return protocols_.size();
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       * @param index The index of the element to return.
       * @return The protocols at the given index.
       */
      public String getProtocols(int index) {
        return protocols_.get(index);
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the protocols at the given index.
       */
      public com.google.protobuf.ByteString
          getProtocolsBytes(int index) {
        return protocols_.getByteString(index);
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       * @param index The index to set the value at.
       * @param value The protocols to set.
       * @return This builder for chaining.
       */
      public Builder setProtocols(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProtocolsIsMutable();
        protocols_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       * @param value The protocols to add.
       * @return This builder for chaining.
       */
      public Builder addProtocols(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProtocolsIsMutable();
        protocols_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       * @param values The protocols to add.
       * @return This builder for chaining.
       */
      public Builder addAllProtocols(
          Iterable<String> values) {
        ensureProtocolsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, protocols_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocols() {
        protocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       * @param value The bytes of the protocols to add.
       * @return This builder for chaining.
       */
      public Builder addProtocolsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProtocolsIsMutable();
        protocols_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:identify.pb.Identify)
    }

    // @@protoc_insertion_point(class_scope:identify.pb.Identify)
    private static final Identify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Identify();
    }

    public static Identify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Identify>
        PARSER = new com.google.protobuf.AbstractParser<Identify>() {
      @Override
      public Identify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Identify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Identify> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Identify> getParserForType() {
      return PARSER;
    }

    @Override
    public Identify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identify_pb_Identify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identify_pb_Identify_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016identify.proto\022\013identify.pb\"\212\001\n\010Identi" +
      "fy\022\027\n\017protocolVersion\030\005 \001(\t\022\024\n\014agentVers" +
      "ion\030\006 \001(\t\022\021\n\tpublicKey\030\001 \001(\014\022\023\n\013listenAd" +
      "drs\030\002 \003(\014\022\024\n\014observedAddr\030\004 \001(\014\022\021\n\tproto" +
      "cols\030\003 \003(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identify_pb_Identify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identify_pb_Identify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identify_pb_Identify_descriptor,
        new String[] { "ProtocolVersion", "AgentVersion", "PublicKey", "ListenAddrs", "ObservedAddr", "Protocols", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
